/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class ConsultCar extends javax.swing.JFrame {

    List<Car> nissanCar = new ArrayList();
    List<Car> lexusCar = new ArrayList();
    List<Car> toyotaCar = new ArrayList();
    List<Car> hondaCar = new ArrayList();
    Car x = new Car();
    DefaultTableModel car;

    public ConsultCar() {
        initComponents();
        car = (DefaultTableModel) CarTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        NissanBtn = new javax.swing.JButton();
        LexusBtn = new javax.swing.JButton();
        ToyotaBtn = new javax.swing.JButton();
        HondaBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        CarTable.setAutoCreateRowSorter(true);
        CarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "State", "Brand", "Model", "Color", "Plate", "Vin", "Chasis", "Price", "Year", "OnStock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CarTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSULT CARS");

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        NissanBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NissanBtn.setText("NISSAN");
        NissanBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NissanBtnMouseClicked(evt);
            }
        });
        NissanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NissanBtnActionPerformed(evt);
            }
        });

        LexusBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LexusBtn.setText("LEXUS");
        LexusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LexusBtnMouseClicked(evt);
            }
        });

        ToyotaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ToyotaBtn.setText("TOYOTA");
        ToyotaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToyotaBtnMouseClicked(evt);
            }
        });

        HondaBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HondaBtn.setText("HONDA");
        HondaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HondaBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NissanBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LexusBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ToyotaBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HondaBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {HondaBtn, LexusBtn, NissanBtn, ToyotaBtn});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(NissanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LexusBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToyotaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HondaBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {HondaBtn, LexusBtn, NissanBtn, ToyotaBtn});

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Remember that you can order the columns according to your taste, you just have to touch it");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NissanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NissanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NissanBtnActionPerformed


    private void NissanBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NissanBtnMouseClicked

        String datos[] = new String[10];
        x.Nissan(nissanCar);
        remove();
        for (int i = 0; i < 10; i++) {
            datos[0] = nissanCar.get(i).getState();
            datos[1] = nissanCar.get(i).getBrand();
            datos[2] = nissanCar.get(i).getModel();
            datos[3] = nissanCar.get(i).getColor();
            datos[4] = nissanCar.get(i).getPlate();
            datos[5] = nissanCar.get(i).getVIN();
            datos[6] = nissanCar.get(i).getChasis();
            datos[7] = nissanCar.get(i).getPrice() + "";
            datos[8] = nissanCar.get(i).getYear() + "";
            datos[9] = nissanCar.get(i).getOnStock();
            car.addRow(datos);

        }
    }//GEN-LAST:event_NissanBtnMouseClicked

    private void LexusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LexusBtnMouseClicked
        String datos[] = new String[10];
        x.Lexus(lexusCar);
        remove();
        for (int i = 0; i < 10; i++) {
            datos[0] = lexusCar.get(i).getState();
            datos[1] = lexusCar.get(i).getBrand();
            datos[2] = lexusCar.get(i).getModel();
            datos[3] = lexusCar.get(i).getColor();
            datos[4] = lexusCar.get(i).getPlate();
            datos[5] = lexusCar.get(i).getVIN();
            datos[6] = lexusCar.get(i).getChasis();
            datos[7] = lexusCar.get(i).getPrice() + "";
            datos[8] = lexusCar.get(i).getYear() + "";
            datos[9] = lexusCar.get(i).getOnStock();
            car.addRow(datos);

        }


    }//GEN-LAST:event_LexusBtnMouseClicked

    private void ToyotaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToyotaBtnMouseClicked
        String datos[] = new String[10];
        x.Toyota(toyotaCar);
        remove();
        for (int i = 0; i < 10; i++) {
            datos[0] = toyotaCar.get(i).getState();
            datos[1] = toyotaCar.get(i).getBrand();
            datos[2] = toyotaCar.get(i).getModel();
            datos[3] = toyotaCar.get(i).getColor();
            datos[4] = toyotaCar.get(i).getPlate();
            datos[5] = toyotaCar.get(i).getVIN();
            datos[6] = toyotaCar.get(i).getChasis();
            datos[7] = toyotaCar.get(i).getPrice() + "";
            datos[8] = toyotaCar.get(i).getYear() + "";
            datos[9] = toyotaCar.get(i).getOnStock();
            car.addRow(datos);

        }
    }//GEN-LAST:event_ToyotaBtnMouseClicked

    private void HondaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HondaBtnMouseClicked
        String datos[] = new String[10];
        x.Honda(hondaCar);
        remove();
        for (int i = 0; i < 10; i++) {
            datos[0] = hondaCar.get(i).getState();
            datos[1] = hondaCar.get(i).getBrand();
            datos[2] = hondaCar.get(i).getModel();
            datos[3] = hondaCar.get(i).getColor();
            datos[4] = hondaCar.get(i).getPlate();
            datos[5] = hondaCar.get(i).getVIN();
            datos[6] = hondaCar.get(i).getChasis();
            datos[7] = hondaCar.get(i).getPrice() + "";
            datos[8] = hondaCar.get(i).getYear() + "";
            datos[9] = hondaCar.get(i).getOnStock();
            car.addRow(datos);

        }
    }//GEN-LAST:event_HondaBtnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    public void remove() {

        int rowsToRemove = car.getRowCount();
        //remove rows from the bottom one by one
        for (int i = rowsToRemove - 1; i >= 0; i--) {
            car.removeRow(i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultCar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultCar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultCar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultCar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CarTable;
    private javax.swing.JButton HondaBtn;
    private javax.swing.JButton LexusBtn;
    private javax.swing.JButton NissanBtn;
    private javax.swing.JButton ToyotaBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
